services:
  pocketbase:
    build:
      context: .
      args:
        PB_VERSION: 0.30.0
    expose:
      - 8090
    volumes:
      - /opt/pocketbase/data:/pb/pb_data
      - /opt/pocketbase/migrations:/pb/pb_migrations
      - /opt/pocketbase/public:/pb/pb_public
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.pocketbase.rule=Host(`pulse-pb.albertec.co.za`)
      - traefik.http.routers.pocketbase.entrypoints=websecure
      - traefik.http.routers.pocketbase.tls.certresolver=letsencrypt
      - traefik.http.services.pocketbase.loadbalancer.server.port=8090

networks:
  dokploy-network:
    external: true
